### PR TITLE
create a SaveLogger.save() method.

### PR DESCRIPTION
**Pull request by shengshuyang**
Associated with my recently reported feature request: Issue https://github.com/pystruct/pystruct/issues/162

### CODE REVIEW

**Comment by amueller** [comment]
Actually this looks pretty nice.
Could you please add at test?

**Comment by shengshuyang** [comment]
OK, so I suppose the test should be added to `test_utils_inference.py`.
Do you have a clear idea on what the test should do? Do we simply call `save()` on several different learners, or do we need to also load the learners back and check for identicality?

**Comment by amueller** [comment]
I would save a learner and load and make sure that they make identical predictions on a toy dataset.
A single learner / model should suffice.
Maybe create a new file, ``test_loggin.py`` The logger is currently tested where the models are tested... I'm not sure if this is great..
Also, I'm not sure how to call the logger at a point in time that is not the end of learning without a breakpoint or callback....

**Comment by shengshuyang** [comment]
Sounds good, I'll create a new file and add the toy test you described. You are right that we can only test the function after training... Well but since `save()` is called by `__call__()`, if it passes existing model tests it should be fine right?
Testing along with the models sounds like a good idea to me. Training complex models are time consuming, if we'd test the logger thoroughly in `test_logging.py`, we will have to go through the whole training process that has been done in model testing.
Gotta go to work - will get back to it tonight.

**Comment by amueller** [comment]
cool thanks.

I just wouldn't test a complex model. You could just do multi-class on iris. That shouldn't take long ;)

**Comment by shengshuyang** [comment]
Test been created. By the way, I have a few general questions about this package, mainly about future plans (approximate inference algorithms to implement etc.), should I open another Issue or is there a forum kind of thing?

**Comment by amueller** [comment]
there is a google group: https://groups.google.com/forum/#!forum/pystruct
Unfortunately I don't have a lot of time to spend on pystruct at the moment, but I'm happy about contributions!

**Comment by shengshuyang** [comment]
Thanks a lot for the link!

**Pull request merged**
